package primus.pawel;

// Crack the pin
// 6kyu
// https://www.codewars.com/kata/5efae11e2d12df00331f91a6/train/java
// 2021-06-11 T:20:41:42
class Exercise_155 {

    public static String MD5(String md5) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
            byte[] array = md.digest(md5.getBytes());
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < array.length; ++i) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1,3));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
        }
        return null;
    }

    public static void main(String[] args) {

        String s = "86aa400b65433b608a9db30070ec60cd";
        System.out.println("Your HashCode Generated by MD5 is: " + MD5(s));
    }





}
